name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    with:
      go-version: '1.24.3'

  docker:
    name: Build Docker Image
    needs: [test]
    uses: ./.github/workflows/docker.yml
    with:
      push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      tag: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'latest' || github.sha }}
      registry: 'ghcr.io'
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: always()
    steps:
    - name: Workflow Summary
      run: |
        echo "## CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
        echo "- Tests: ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Docker: ${{ needs.docker.result }}" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ needs.test.result }}" == "success" && "${{ needs.docker.result }}" == "success" ]]; then
          echo "✅ All checks passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Some checks failed. Please review the logs." >> $GITHUB_STEP_SUMMARY
        fi 